### PR TITLE
fix(tags): exclude non-specified

### PR DESCRIPTION
**Pull request by s0up4200**
Previously, omegabrr was adding all monitored shows/movies to the list, regardless of whether they had the specified tags in `tagsInclude`. With this PR, omegabrr will now only add shows/movies with the tag(s) specified in `tagsInclude` in config.yaml.

If `tagsInclude` is not used, all monitored shows/movies (except those part of `tagsExclude`) will be added to the list.

### CODE REVIEW

**Comment by bakerboy448** [comment]
This logic should allow both to work

Initially filter include all series for only tagsInclude
Then remove any series that exist in tagsExclude

**Comment by s0up4200** [comment]
Are you referring to a scenario where a show has tags in both tagsInclude and tagsExclude? Those are not added to autobrr.

**Comment by zze0s** [comment]
> Are you referring to a scenario where a show has tags in both tagsInclude and tagsExclude? Those are not added to autobrr.
> 
> EDIT: Answered and confirmed on Discord

What was the conclusion here? Needed or not?

**Comment by s0up4200** [comment]
This PR isn't needed. The program is already functioning as intended.

If `tagsInclude` is used, then only titles with those tags are added. If the titles also have a tag specified in `tagsExclude`, it will be excluded.

**Comment by s0up4200** [comment]
Not needed.

**Pull request closed without merging**
